// <auto-generated />
using System;
using Battleship.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Battleship.Migrations
{
    [DbContext(typeof(BattleshipDBContext))]
    partial class BattleshipDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Battleship.Models.HighScore", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("AccuracyScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date_Of_Win")
                        .HasColumnType("datetime2");

                    b.HasKey("PlayerId");

                    b.ToTable("HighScores");
                });

            modelBuilder.Entity("Battleship.Models.Inventory", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Cash")
                        .HasColumnType("int");

                    b.Property<int>("Power1")
                        .HasColumnType("int");

                    b.Property<int>("Power2")
                        .HasColumnType("int");

                    b.Property<int>("Power3")
                        .HasColumnType("int");

                    b.HasKey("PlayerId");

                    b.ToTable("Inventories");
                });
#pragma warning restore 612, 618
        }
    }
}
